name: Run tests on PR

on:  
  pull_request:
    branches: [ master ]

jobs:  
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - run: npm ci
    - run: npm test
